DROP TABLE IMAM_MUAJJIN;
DROP TABLE MASHJID_COMITTE;
DROP TABLE EQUIPMENT;
DROP TABLE EXPENDATURE;
DROP TABLE EQUIPMENT_SET;
DROP TABLE DESIGNATION_SET;
DROP TABLE MASJID;
DROP TABLE CITY;

CREATE TABLE CITY (
	CITY_ID  INTEGER AUTO_INCREMENT,
	CITY_NAME VARCHAR(20),
	DIVISION VARCHAR(20),
	PRIMARY KEY(CITY_ID)
);

CREATE TABLE MASJID (
	M_ID  INTEGER AUTO_INCREMENT,
	NAME VARCHAR(20),
	ADDRESS VARCHAR(20) UNIQUE,
	CITY_ID  INTEGER,
	AREA DECIMAL(5,2),
	ESTD DATE,
	PRIMARY KEY(M_ID),
	FOREIGN KEY(CITY_ID) REFERENCES CITY(CITY_ID) ON DELETE CASCADE
);

CREATE TABLE DESIGNATION_SET (
	DESIGNATION_ID INTEGER AUTO_INCREMENT,
	DESIGNATION_NAME VARCHAR(20),
	PRIMARY KEY(DESIGNATION_ID)
);

CREATE TABLE IMAM_MUAJJIN (
	M_ID  INTEGER,
	EMPLOYEE_ID  INTEGER AUTO_INCREMENT,
	NAME VARCHAR(20),
	DESIGNATION_ID INTEGER,
	PHONE_NUM VARCHAR(13) UNIQUE, 
	PRIMARY KEY(EMPLOYEE_ID),
	FOREIGN KEY(M_ID) REFERENCES MASJID(M_ID) ON DELETE CASCADE,
	FOREIGN KEY(DESIGNATION_ID) REFERENCES DESIGNATION_SET(DESIGNATION_ID) ON DELETE CASCADE
);

CREATE TABLE MASHJID_COMITTE(
	M_ID  INTEGER,
	MEMBER_ID  INTEGER AUTO_INCREMENT,
	NAME VARCHAR(20),
	PHONE_NUM VARCHAR(13) UNIQUE, 
	DESIGNATION_ID INTEGER,
	PRIMARY KEY(MEMBER_ID),
	FOREIGN KEY(M_ID) REFERENCES MASJID(M_ID) ON DELETE CASCADE,
	FOREIGN KEY(DESIGNATION_ID) REFERENCES DESIGNATION_SET(DESIGNATION_ID) ON DELETE CASCADE
);

CREATE TABLE EQUIPMENT_SET (
	ITEM_ID INTEGER AUTO_INCREMENT,
	NAME VARCHAR(16),
	PRIMARY KEY(ITEM_ID)
);

CREATE TABLE EQUIPMENT (
	M_ID  INTEGER,
	ITEM_ID INTEGER,
	COUNT DECIMAL(5),
	FOREIGN KEY(M_ID) REFERENCES MASJID(M_ID) ON DELETE CASCADE,
	FOREIGN KEY(ITEM_ID) REFERENCES EQUIPMENT_SET(ITEM_ID) ON DELETE CASCADE
);

CREATE TABLE EXPENDATURE (
	M_ID  INTEGER,
	YEAR DECIMAL(4),
	AMOUNT DECIMAL(10),
	TOTAL_AMOUNT DECIMAL(20) DEFAULT 0,
	FOREIGN KEY(M_ID) REFERENCES MASJID(M_ID) ON DELETE CASCADE
);
